[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "YOLOv7"
authors = [{name = "lucasjin", email = "jinfagang19@163.com"}]
dynamic = ["version", "description"]
